# Generated by Django 2.2.6 on 2019-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAccount', '0003_checkedemail'),
        ('users', '0002_auto_20190509_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailaccount',
            field=models.ManyToManyField(to='EmailAccount.EmailAccount'),
        ),
    ]
