# Generated by Django 2.2.6 on 2019-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAccount', '0002_auto_20191122_1400'),
        ('users', '0002_auto_20190509_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_email',
            field=models.ManyToManyField(to='EmailAccount.EmailAccount'),
        ),
    ]
