# Generated by Django 2.2.6 on 2019-11-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailauth', '0002_auto_20191122_1326'),
        ('users', '0002_auto_20190509_1707'),
        ('EmailAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobEmail',
            new_name='EmailAccount',
        ),
    ]
