# Generated by Django 2.2.6 on 2019-11-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAccount', '0002_auto_20191122_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedEmail',
            fields=[
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailAccount.EmailAccount')),
            ],
        ),
    ]
