# Generated by Django 2.2.6 on 2019-12-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAccount', '0007_auto_20191201_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckedMessage',
        ),
    ]
