# Generated by Django 2.2.6 on 2019-12-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAccount', '0009_checkedmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckedMessage',
        ),
    ]
