# Generated by Django 2.2.6 on 2019-12-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAccount', '0011_checkedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedmessage',
            name='body_text',
            field=models.TextField(null=True),
        ),
    ]
