# Generated by Django 2.2.6 on 2019-11-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailauth', '0004_auto_20191126_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmailCredential',
        ),
    ]
