# Generated by Django 2.2.6 on 2019-11-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailauth', '0005_delete_gmailcredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CredentialsModel',
        ),
    ]
